import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import Head from "next/head";
import Footer from "./components/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Recipe Book",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
      </Head>
      <body className="flex flex-col min-h-screen bg-yellow-50">
        <Navbar />
        <main className="flex-grow bg-yellow-50">{children}</main>
        <Footer />
      </body>
    </html>
  );
}

